a = ["EAT SOMETHING DELICIOUSE TODAY.",
"TALK TO YOUR BEST FREIND FOR 5 MINS",
"PLAY DUMBSHERADS WITH YOUR FREINDS TODAY.",
"PLAY TAMBOLA WITH YOUR FREINDS TODAY.",
"PREPARE SOMETHING DELICIOUSE FOR YOUR FAMILY MEMBERS TODAY.",
"PLAY A BOARD GAME WITH YOUR FAMILY MEMBERS.",       
"HAVE A DANCE COMPETITION WITH YOUR FAMILY.",
"GO TO PLAY ANY SPORT YOU LIKE.",]

for e in a:
    print(e.title())